### ISSUE TITLE
Building on custom trained YOLOv5s tflite model

### ISSUE THREAD

**Issue by axlecky** [lp6m/yolov5s_android#10]
Hi, I trained a yolov5s model on a custom dataset and have an exported fp16 tflite model. How do I use it to build this app? Thanks

**Comment by lp6m** [comment]
To build application by yourself, copy ./tflite_model/*.tflite to app/tflite_yolov5_test/app/src/main/assets/, and build on Android Studio.

**Comment by axlecky** [comment]
Hi @lp6m, thanks for the reply, I have done that. However when running the app on my phone the camera fails to open and it shows an error msg "Detector could not be initialized". When trying to run inference on an uploaded image, the error msg shows "Model load failed: yolov5s_fp32_640.tflite"

**Comment by lp6m** [comment]
Hmm,, OK, I will write the tutorial to build with custom trained YOLOv5 model when I have time...

**Comment by lp6m** [comment]
@axlecky Can you attach your custom tflite model? If possible, please attach 4 files with different input sizes and calculation precision.  
  
- yolov5s_fp32_320.tflite
- yolov5s_fp32_640.tflite
- yolov5s_int8_320.tflite
- yolov5s_int8_640.tflite

**Comment by axlecky** [comment]
@lp6m thanks for the response. I have the fp16 model, however do note that my input size is 416.

Attached file:
[best-fp16.zip](https://github.com/lp6m/yolov5s_android/files/8591394/best-fp16.zip)

**Comment by axlecky** [comment]
Hi @lp6m. Is there any update to this issue? I hope to use this for my report which is due soon. Thanks!

**Comment by alexmihalyk23** [comment]
Hi @lp6m. When i create custom tflite model i have got a error with identity. Identity in my custom model is 21 but in code only 255. How to convert model for working model. I change 255 to 21 in out1 out2 and out3 but bbox on image work incorrectly

**Comment by lp6m** [comment]
@alexmihalyk23 The output num is calculated by the following formula: `(class_num + 5) * 3`.  
Coco dataset has 80 classes, so `(80+5)*3 = 255`

**Comment by SEANIRLO** [comment]
> To build application by yourself, copy ./tflite_model/*.tflite to app/tflite_yolov5_test/app/src/main/assets/, and build on Android Studio.

I can't find the assets folder in project. There are cpp, java and res folders only. What should I do? Thanks!

**Comment by zenetio** [comment]
I guess you can create the directory by yourself.

**Comment by lp6m** [comment]
I write the tutorial for custom model & dataset. please check.  
https://github.com/lp6m/yolov5s_android/issues/14

**Comment by SEANIRLO** [comment]
Thank you for your tutorial! I've checked that and it was of great help :D











肖汉

北京邮电大学/本科生/信息与通信工程学院



北京




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Jun 25, 2022 00:03 AM
To: ***@***.***&gt;; 
Cc: &nbsp;"Sean ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [lp6m/yolov5s_android] Building on custom trained YOLOv5s tflite model (Issue #10)

&nbsp;



 
I write the tutorial for custom model &amp; dataset. please check.
 #14

**Comment by liiicon** [comment]
> 嗨，我在自定义数据集上训练了一个 yolov5s 模型，并导出了一个导出的 fp16 tflite 模型。如何使用它来构建此应用程序？谢谢



> 嗨，感谢您的回复，我已经做到了。但是，当我在手机上运行该应用程序时，相机无法打开，并显示错误消息“无法初始化检测器”。尝试对上传的图像运行推理时，错误 msg 显示“模型加载失败：yolov5s_fp32_640.tflite”

请问你是如何解决的？

**Comment by lp6m** [comment]
@liiicon please check that you copy tflite model file into Android project directory. And also you can get the detail error in debug mode and please tell me the stack trace.
