### ISSUE TITLE
TfliteRunner custom context

### ISSUE THREAD

**Issue by alexmihalyk23** [lp6m/yolov5s_android#11]
How to change TfliteRunner for working with custom Activity in manifest. I'am using MAppication class for starting app. MainActivity open in MApplication 
![image](https://user-images.githubusercontent.com/35634279/168831645-cf52d515-eb5e-4d04-9f72-3da0bc321163.png)

**Comment by lp6m** [comment]
The topic of this issue is application development techniques and is outside the scope of this project.
