### ISSUE TITLE
model is not a valid Flatbuffer file

### ISSUE THREAD

**Issue by kingmacth** [lp6m/yolov5s_android#12]
我自己编译会提示model is not a valid Flatbuffer file。模型用的是https://github.com/lp6m/yolov5s_android/tree/master/tflite_model文件夹下到。你到APP使用到时这个四个模型文件么。

**Comment by lp6m** [comment]
I write the tutorial for custom model & dataset. please check.  
https://github.com/lp6m/yolov5s_android/issues/14
