### ISSUE TITLE
why when using your model so fast but my custom model is very slow on mobile ?

### ISSUE THREAD

**Issue by Houangnt** [lp6m/yolov5s_android#15]

**Comment by lp6m** [comment]
Attach your tflite model.

**Comment by lp6m** [comment]
https://github.com/lp6m/yolov5s_android/issues/14#issuecomment-1167746689
If the precision of your model is low and the `conf_thresh` parameter is low, there are many result bounding boxes.  
Many bounding boxes cause the lower performance.
