### ISSUE TITLE
the release apk does not work if I open the camera, the "fps" is not chaging at all

### ISSUE THREAD

**Issue by yspisgod** [lp6m/yolov5s_android#19]

**Comment by lp6m** [comment]
- What smartphone are you using? 
- Please check the permission setting.

**Comment by yspisgod** [comment]
- [https://github.com/yspisgod/yolov3-tiny-data/blob/main/system.jpg ] 
this is my smartphone info

I have grant all permission

**Comment by lp6m** [comment]
Does inference on local images without cameras work well?

**Comment by yspisgod** [comment]
yes ,it works well on local image

**Comment by yspisgod** [comment]
https://github.com/yspisgod/yolov3-tiny-data/blob/main/debuginfo.jpg

this is a snapshot from android studio

**Comment by yspisgod** [comment]
CameraActivity.onImageAvailable 
this method never be called

**Comment by yspisgod** [comment]
https://github.com/yspisgod/yolov3-tiny-data/blob/main/fix.jpg

I change  the  code , force to use CameraConnectionFragment, then it works well now

**Comment by daydayupchen** [comment]
我也遇到了这个问题，同是华为
