### ISSUE TITLE
Higher confidence but smaller bbox size

### ISSUE THREAD

**Issue by zenetio** [lp6m/yolov5s_android#20]
I have an interesting inference output. The image below is using conf=0.84 and IoU=0.30
[![image](https://user-images.githubusercontent.com/578337/179371623-11b9e426-41ce-43d8-908b-0b84f32a5010.png)](url)
First, the bboxes are smaller than the objects. Second, somehow when I have more than one bbox to the same object as shown in the image for bbox yellow and blue, note that in the yellow case, the higher prediction 93.82 the bbox is smaller than the 89.70 that has a bigger bbox. The same happens with blue case where the higher prediction 92.96 the bbox is smaller than the 91.48 has a bigger bbox. If I decrease IoU or increase the confidence, I will get only one bbox for yellow and blue with higher conf but the ones removed had a better bbox size when compared with their objects. Why is the algorithm assigning lower conf to bboxes with a larger size (near the object size) and higher conf to bboxes with smaller sizes?
Any hint on this?

**Comment by lp6m** [comment]
@zenetio Try inference from local images instead of from camera images.
Show the results of the host environment and the results of the android application.
The implementation of NMS processing may not match perfectly between the host and the app.
