### ISSUE TITLE
no node named Conv_253

### ISSUE THREAD

**Issue by yspisgod** [lp6m/yolov5s_android#22]
when i run 
python3 /opt/intel/openvino_2021.3.394/deployment_tools/model_optimizer/mo.py  --input_model yolov5s.onnx  --input_shape [1,3,640,640]  --output_dir ./openvino  --data_type FP32  --output Conv_253,Conv_302,Conv_351

it seems that "-output" is unnecessary

**Comment by lp6m** [comment]
Output node names are different in different environment, and yolov5 version.  Check the output node name in Netron.

We remove the yolov5 head layers through model conversion, so '--output' is mandatory.
