### ISSUE TITLE
Run inference in GUI gives me `Inference failed`

### ISSUE THREAD

**Issue by mikel-brostrom** [lp6m/yolov5s_android#24]
I managed to build my app and import a model but when I press **RUN INFERENCE** I get: 

```bash
Inference failed : Cannot copy from a TensorFlowLite tensor (StatufulPartitionedCall:2) with shape [1, 20, 20, 51] to a Java object with shape [1, 40 , 40, 51]
```

**Comment by lp6m** [comment]
Confirm that your converted tflite model has 3 output on netron.  
If it is confirmed and still fail to run inference, the order of the three outputs may not be as expected.  
In that case, changing the order may work.
https://github.com/lp6m/yolov5s_android/blob/master/app/tflite_yolov5_test/app/src/main/java/com/example/tflite_yolov5_test/TfliteRunner.java#L147-L149

**Comment by mikel-brostrom** [comment]
Thank you for your time @lp6m! I see the following in Netron:

![Screenshot from 2022-07-29 11-56-04](https://user-images.githubusercontent.com/18719680/182083105-08d0b6d3-0019-4d08-858d-6982fe516114.png)

So, yes, it has 3 outputs. My OpenVINO export command is:

```bash
mo \
--input_model /datadrive/mikel/yolov5/runs/train/yolov5s_valuables_trash/weights/best.onnx \
--output_dir /datadrive/mikel/yolov5/runs/train/yolov5s_valuables_trash/weights/openvino \
--data_type FP32 \
--output Conv_198,Conv_217,Conv_236
```

**Comment by mikel-brostrom** [comment]
> changing the order may work

You solution works, I changed this

```bash
        outputMap.put(0, this.rawres.out1);
        outputMap.put(1, this.rawres.out2);
        outputMap.put(2, this.rawres.out3);
```

to

```bash
        outputMap.put(0, this.rawres.out1);
        outputMap.put(2, this.rawres.out2);
        outputMap.put(1, this.rawres.out3);
```

Is there a way of forcing the output  order shape with the `mo` command? If there is, it could be added to the commands in your Custom Model Integration Tutorial :smile:
