### ISSUE TITLE
How can I adjust the output of my TFLite exported model in order to make it work with your app

### ISSUE THREAD

**Issue by ppl520zfl** [lp6m/yolov5s_android#26]
Hi!

I tried my own tflite model trained with yolov5 on your app, but get the flow error:

**Cannot copy from a TensorFlowLite tensor (StatefulPartitionedCall:0) with shape [1, 6300, 7] to a Java object with shape [1, 40, 40, 255].**

your models have 4 outputs, but my models only have 3 outputs, what should i do to make my model work.

Thanks!

**Comment by lp6m** [comment]
It seems that your model is not converted correctly. The converted model should have 4-dimension output.
https://github.com/lp6m/yolov5s_android/tree/master/convert_model
