### ISSUE TITLE
letterbox implementation?

### ISSUE THREAD

**Issue by dsbyprateekg** [lp6m/yolov5s_android#28]
Hi,

Can you please update your code with the letterbox method?
I am trying to use with my custom-trained model but seeing no detection due to resizing issue.
So I need to add letterbox.

**Comment by lp6m** [comment]
You can implement by modifying this code: 
We welcome to your PR
https://github.com/lp6m/yolov5s_android/blob/master/app/tflite_yolov5_test/app/src/main/java/com/example/tflite_yolov5_test/TfliteRunner.java#L113-L115
