### ISSUE TITLE
Class probability

### ISSUE THREAD

**Issue by K4elthaz** [lp6m/yolov5s_android#29]
Helloo do you know how can i show the class probability? for example
4 classes {0: cat,1: dog,2: bird,3: fish}

Detected Cat 0.9 : Dog .01 : Bird 0.0 : Fish : 0.0
something like that thank you

**Comment by lp6m** [comment]
You can get probabilities for each class from here: https://github.com/lp6m/yolov5s_android/blob/master/app/tflite_yolov5_test/app/src/main/cpp/postprocess.cpp#L46C47-L53
