### ISSUE TITLE
did int8 inferece succeed in android(arm)?

### ISSUE THREAD

**Issue by moyans** [lp6m/yolov5s_android#6]

**Comment by lp6m** [comment]
As described in [README.md](https://github.com/lp6m/yolov5s_android#int8-model), int8 inference on android CPU works.  
But when applying NNAPI delegate (hexagon-dsp) for int8 model, the inference does not work.

**Comment by moyans** [comment]
I tried, but I failed

**Comment by lp6m** [comment]
@moyans What error occurs? Did you try the apk on github release?
